import 'dart:typed_data';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/reports_repository.dart';
import '../models/platform_report.dart';
import '../../auth/presentation/auth_notifier.dart';

class ReportsState {
  final List<PlatformReport> reports;
  final List<Map<String, dynamic>> platforms;
  final List<Map<String, dynamic>> supervisors;
  final bool loading;
  final String? error;
  final String? selectedPlatformId;
  final ReportFrequency selectedFrequency;
  final DateTime selectedDate;

  ReportsState({
    this.reports = const [],
    this.platforms = const [],
    this.supervisors = const [],
    this.loading = false,
    this.error,
    this.selectedPlatformId,
    this.selectedFrequency = ReportFrequency.daily,
    DateTime? selectedDate,
  }) : selectedDate = selectedDate ?? DateTime.now();

  ReportsState copyWith({
    List<PlatformReport>? reports,
    List<Map<String, dynamic>>? platforms,
    List<Map<String, dynamic>>? supervisors,
    bool? loading,
    String? error,
    String? selectedPlatformId,
    ReportFrequency? selectedFrequency,
    DateTime? selectedDate,
  }) {
    return ReportsState(
      reports: reports ?? this.reports,
      platforms: platforms ?? this.platforms,
      supervisors: supervisors ?? this.supervisors,
      loading: loading ?? this.loading,
      error: error,
      selectedPlatformId: selectedPlatformId ?? this.selectedPlatformId,
      selectedFrequency: selectedFrequency ?? this.selectedFrequency,
      selectedDate: selectedDate ?? this.selectedDate,
    );
  }
}

class ReportsNotifier extends StateNotifier<ReportsState> {
  final ReportsRepository _repo;
  final String userId;
  final String userRole;

  ReportsNotifier(this._repo, this.userId, this.userRole) : super(ReportsState()) {
    _init();
  }

  Future<void> _init() async {
    state = state.copyWith(loading: true);
    try {
      // Fetch ALL platforms safely first as a robust base
      final allPlatforms = await _repo.fetchPlatforms();
      List<Map<String, dynamic>> platforms = allPlatforms;
      
      // Attempt to filter by assignment if Supervisor
      if (userRole == 'Supervisor') {
        try {
          final assigned = await _repo.fetchAssignedPlatforms(userId);
          if (assigned.isNotEmpty) {
            platforms = assigned;
          }
        } catch (e) {
          // Silently fallback to all platforms if the query fails
        }
      }
      
      List<Map<String, dynamic>> supervisors = [];
      try {
        supervisors = await _repo.fetchSupervisors();
      } catch (e) {
        // Silently fallback to empty supervisors if query fails
      }
      
      state = state.copyWith(
        platforms: platforms,
        supervisors: supervisors,
        selectedPlatformId: platforms.length == 1 ? platforms[0]['id'] as String : null,
      );
      
      // Loading of reports is also wrapped internally, so it's safe to proceed
      await loadReports();
    } catch (e) {
      state = state.copyWith(loading: false, error: e.toString());
    }
  }

  Future<void> loadReports() async {
    state = state.copyWith(loading: true);
    try {
      // If Supervisor, only see their reports (unless they manage multiple platforms)
      // The requirement says "each supervisores manage seprate platforms"
      final filterSupervisorId = (userRole == 'Supervisor') ? userId : null;
      
      final reports = await _repo.fetchReports(
        platformId: state.selectedPlatformId,
        supervisorId: filterSupervisorId,
        frequency: state.selectedFrequency,
      );
      
      state = state.copyWith(reports: reports, loading: false);
    } catch (e) {
      state = state.copyWith(loading: false, error: e.toString());
    }
  }

  void setFrequency(ReportFrequency freq) {
    state = state.copyWith(selectedFrequency: freq);
    loadReports();
  }

  void setPlatform(String? platformId) {
    state = state.copyWith(selectedPlatformId: platformId);
    loadReports();
  }

  void setDate(DateTime date) {
    state = state.copyWith(selectedDate: date);
    loadReports();
  }

  Future<void> uploadReport({
    required String fileName,
    required String fileType,
    required String fileUrl,
    required DateTime reportDate,
    required ReportFrequency frequency,
    required String platformId,
    Uint8List? fileBytes,
  }) async {
    state = state.copyWith(loading: true);
    try {
      String finalFileUrl = fileUrl;
      
      // Upload to Supabase Storage if bytes provided
      if (fileBytes != null) {
        finalFileUrl = await _repo.uploadReportFile(
          fileBytes: fileBytes,
          fileName: fileName,
          userId: userId,
        );
      }

      final report = PlatformReport(
        id: '', // Will be generated by DB
        platformId: platformId,
        platformName: '', // Fetched in UI or Repo
        supervisorId: userId,
        supervisorName: '', // Fetched in UI or Repo
        reportDate: reportDate,
        frequency: frequency,
        fileUrl: finalFileUrl,
        fileName: fileName,
        fileType: fileType,
        uploadedAt: DateTime.now(),
      );
      
      await _repo.uploadReport(report);
      await loadReports();
    } catch (e) {
      state = state.copyWith(loading: false, error: e.toString());
    }
  }
}

final reportsRepositoryProvider = Provider<ReportsRepository>((ref) {
  return ReportsRepository(Supabase.instance.client);
});

final reportsProvider = StateNotifierProvider.autoDispose<ReportsNotifier, ReportsState>((ref) {
  final repo = ref.watch(reportsRepositoryProvider);
  final auth = ref.watch(authProvider);
  return ReportsNotifier(
    repo,
    auth.user?.id ?? '',
    auth.profile?.role ?? 'Rider',
  );
});
